flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- Chart-diagrams-1.5.4
- OneTuple-0.2.1
- SVGFonts-1.5.0.0
- arithmoi-0.4.1.3
- mersenne-random-pure64-0.2.0.5
- text-1.2.2.1
- tuple-0.3.0.2
resolver: lts-5.15
